---
title: "STAT432_FinalProject"
output: html_document
date: "2025-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization

```{r}
# packages
library(dplyr)
library(tidyverse)
library(randomForest)
library(nnet)
library(caret)
library(e1071)
library(class)
library(glmnet)
library(car)
library(MASS)
library(ROCR)
```

# Importing and Processing Data

```{r}
# importing data
data <- read.csv("output.csv")

# adding majority vote column
data$highest_party <- apply(data[, c("DEMOCRAT", "REPUBLICAN")], 1, function(row) {
  if (all(is.na(row))) {
    NA  # or "Unknown", if you prefer
  } else {
    parties <- c("Democratic", "Republican")
    parties[which.max(row)]
  }
})

data$highest_party <- ifelse(data$highest_party == "Republican", 1, 0)


# adding total turnout column
data$total_turnout <- data$DEMOCRAT + data$REPUBLICAN + data$OTHER

data$dem_pct <- data$DEMOCRAT/data$total_turnout
data$rep_pct <- data$REPUBLICAN/data$total_turnout
data$oth_pct <- data$OTHER/data$total_turnout
data <- na.omit(data)
head(data)
```

```{r}
### preprocessing
train_idx <- sample(1:nrow(data), 0.8 * nrow(data))
train_data <- data[train_idx, ]
test_data <- data[-train_idx, ]
y_train <- train_data$highest_party
y_test <- test_data$highest_party
X_train <- train_data[, -which(names(train_data) == "highest_party")]
X_test <- test_data[, -which(names(test_data) == "highest_party")]
```

# Model 1 - Logistic Regression

```{r}
### fitting model
# full model
set.seed(7)
pen_train_data <- subset(train_data, select = -c(FIPS, STATE, ST_ABBR, COUNTY, LOCATION, POPCHANGE, dem_pct, oth_pct, rep_pct, DEMOCRAT, OTHER, REPUBLICAN, total_turnout, Male_percentage_estimate))
pen_test_data <- subset(test_data, select = names(pen_train_data))
pen_X_test <- model.matrix(highest_party ~ ., data = pen_test_data)[,-1]

#log_model <- glm(highest_party ~ ., data = log_train_data, family = binomial())
#summary(log_model)

# Prepare model matrix and response
x <- model.matrix(highest_party ~ ., data = pen_train_data)[, -1]
y <- pen_train_data$highest_party

# Fit logistic regression with regularization
cv_fit <- cv.glmnet(x, y, family = "binomial", alpha = 1)  # alpha = 1 is lasso

# View the best lambda
best_lambda <- cv_fit$lambda.min
final_model <- glmnet(x, y, family = "binomial", alpha = 1, lambda = best_lambda)

pred_probs <- predict(cv_fit, newx = pen_X_test, s = "lambda.min", type = "response")
pred_classes <- ifelse(pred_probs > 0.5, 1, 0)

# Accuracy
mean(pred_classes == y_test)

# Optional: Confusion matrix
table(Predicted = pred_classes, Actual = y_test)

roc.LASSO <- prediction(pred_probs, pen_test_data$highest_party)
# calculating the ROC curve
perf.LASSO <- performance(roc.LASSO,"tpr","fpr")
plot(perf.LASSO, colorize=TRUE)
auc.LASSO <- performance(roc.LASSO, measure = "auc")
auc_value <- auc.LASSO@y.values[[1]]
print(auc_value)
```

## Analysis

```{r}

```

# Model 2 - K-Nearest Neighbors (KNN)

```{r}
### building model
X_train <- data.frame(lapply(X_train, function(x) as.numeric(as.factor(x))))
X_test <- data.frame(lapply(X_test, function(x) as.numeric(as.factor(x))))
knn_fit <- knn(train = X_train, test = X_test, cl = y_train, k = 5)

# confusion matrix
table(Predicted = knn_fit, Actual = y_test)
accuracy <- sum(knn_fit == y_test) / length(y_test)
cat("Accuracy:", accuracy)
```

# Model 3 - Random Forest

```{r}
data$highest_party <- as.factor(data$highest_party)

random_forest_model <- randomForest(highest_party ~ . - FIPS - STATE - ST_ABBR - COUNTY - LOCATION - POPCHANGE - dem_pct - oth_pct - rep_pct - DEMOCRAT - OTHER - REPUBLICAN - total_turnout - Male_percentage_estimate, data = data, ntree = 500, importance = TRUE)
print(random_forest_model)
```

# Model 4 - Support Vector Machine

```{r}
svm_fit <- svm(highest_party ~ . - FIPS - STATE - ST_ABBR - COUNTY - LOCATION - POPCHANGE - dem_pct - oth_pct - rep_pct - DEMOCRAT - OTHER - REPUBLICAN - total_turnout - Male_percentage_estimate, data = data, kernel = "radial", scale = FALSE) # use radial kernel because data is not linearly separable
summary(svm_fit)
```

```{r}
svm_pred <- predict(svm_fit, data)
confusion <- confusionMatrix(svm_pred, data$highest_party)
print(confusion)
```
